// GENERATED by build_data.py from README.md -- do not edit by hand.
// Re-run `python3 build_data.py` after pulling upstream changes.
window.CP2GO = {
 "months": [
  {
   "n": 1,
   "weeks": [
    {
     "n": 1,
     "title": "Dynamic Programming",
     "sections": [
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "3f7200a32e",
         "t": "Dynamic Programming Notes Hackerearth",
         "u": "https://www.hackerearth.com/practice/notes/dynamic-programming-i-1/",
         "k": "problem",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "General"
        },
        {
         "id": "7cef3b5f12",
         "t": "DP Tutorial involving grids",
         "u": "https://www.hackerearth.com/practice/notes/dynamic-programming-problems-involving-grids/",
         "k": "read",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Reading Material"
        },
        {
         "id": "5b4257a99f",
         "t": "TopCoder Tutorial on DP",
         "u": "https://www.topcoder.com/community/competitive-programming/tutorials/dynamic-programming-from-novice-to-advanced/",
         "k": "read",
         "d": 0,
         "p": "TopCoder",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Solve the following classical problems",
       "k": "problem",
       "items": [
        {
         "id": "4a987c806e",
         "t": "Coin change problem",
         "u": "https://www.hackerrank.com/challenges/coin-change/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following classical problems"
        },
        {
         "id": "b2f6450779",
         "t": "Unbounded Knapsack",
         "u": "https://www.hackerrank.com/challenges/unbounded-knapsack/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following classical problems"
        },
        {
         "id": "43378a554f",
         "t": "Longest common subsequence",
         "u": "https://www.hackerrank.com/challenges/dynamic-programming-classics-the-longest-common-subsequence/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following classical problems"
        }
       ]
      },
      {
       "t": "Solve the following MISC problems",
       "k": "problem",
       "items": [
        {
         "id": "feeb3762b6",
         "t": "Cutting",
         "u": "https://codeforces.com/problemset/problem/998/B",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "af8bdca320",
         "t": "The Great Julya Calendar",
         "u": "https://codeforces.com/problemset/problem/331/C1",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "c44b4f8e00",
         "t": "Shashlik Cooking",
         "u": "https://codeforces.com/problemset/problem/1040/B",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "ca97c7b189",
         "t": "Divisibility by Eight",
         "u": "https://codeforces.com/problemset/problem/550/C",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "1a0e3fc174",
         "t": "Bishwock",
         "u": "https://codeforces.com/problemset/problem/991/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "2f0ea934db",
         "t": "Functions again",
         "u": "https://codeforces.com/problemset/problem/788/A",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "f07ce2156f",
         "t": "An impassioned circulation of affection",
         "u": "https://codeforces.com/problemset/problem/814/C",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "3a7ef4b0b3",
         "t": "Color Stripe",
         "u": "https://codeforces.com/problemset/problem/219/C",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "e99393d5fe",
         "t": "Prime XOR",
         "u": "https://www.hackerrank.com/challenges/prime-xor/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        },
        {
         "id": "58753f9d70",
         "t": "HackerRank City",
         "u": "https://www.hackerrank.com/challenges/hr-city/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Solve the following MISC problems"
        }
       ]
      },
      {
       "t": "Contests",
       "k": "contest",
       "items": [
        {
         "id": "61f5eb25b6",
         "t": "Educational DP contest on AtCoder",
         "u": "https://atcoder.jp/contests/dp",
         "k": "contest",
         "d": 0,
         "p": "AtCoder",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        },
        {
         "id": "b5e39d2472",
         "t": "DSA Learning Series: Week 7 - DP By CodeChef",
         "u": "https://www.codechef.com/LRNDSA07",
         "k": "contest",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        },
        {
         "id": "c1dcf55a8f",
         "t": "Marathon DP - 01",
         "u": "https://vjudge.net/contest/202878",
         "k": "contest",
         "d": 0,
         "p": "vJudge",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        },
        {
         "id": "762bb8c299",
         "t": "V Planet DP - 2",
         "u": "https://codeforces.com/group/hK6hgc8x94/contest/222255",
         "k": "contest",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        },
        {
         "id": "3a38599fca",
         "t": "V Planet DP - 3",
         "u": "https://codeforces.com/group/hK6hgc8x94/contest/222261",
         "k": "contest",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        },
        {
         "id": "4d67d6fc4f",
         "t": "V Planet DP Week 5",
         "u": "https://codeforces.com/group/hK6hgc8x94/contest/238061",
         "k": "contest",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 1,
         "s": "Contests"
        }
       ]
      }
     ]
    },
    {
     "n": 2,
     "title": "Trees & Graphs",
     "sections": [
      {
       "t": "Trees",
       "k": "problem",
       "items": [
        {
         "id": "4bacdbcf60",
         "t": "Diameter of a Binary Tree",
         "u": "https://leetcode.com/problems/diameter-of-binary-tree/",
         "k": "problem",
         "d": 1,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        },
        {
         "id": "18a6d54809",
         "t": "Path Sum",
         "u": "https://leetcode.com/problems/path-sum/",
         "k": "problem",
         "d": 1,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        },
        {
         "id": "26f5cdcb39",
         "t": "K-th smallest element in a BST",
         "u": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
         "k": "problem",
         "d": 2,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        },
        {
         "id": "56ffca38e9",
         "t": "Find duplicate subtrees",
         "u": "https://leetcode.com/problems/find-duplicate-subtrees/",
         "k": "problem",
         "d": 2,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        },
        {
         "id": "e7470eace0",
         "t": "Lowest Common Ancestor of a binary tree",
         "u": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
         "k": "problem",
         "d": 2,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        },
        {
         "id": "776d39184b",
         "t": "Sum of distances in tree",
         "u": "https://leetcode.com/problems/sum-of-distances-in-tree/",
         "k": "problem",
         "d": 3,
         "p": "LeetCode",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Trees"
        }
       ]
      },
      {
       "t": "BFS and DFS",
       "k": "problem",
       "items": [
        {
         "id": "ecbe05d666",
         "t": "Ones and Zeroes",
         "u": "https://www.spoj.com/problems/ONEZERO/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "BFS and DFS"
        },
        {
         "id": "15b700350d",
         "t": "Prime Path",
         "u": "https://www.spoj.com/problems/PPATH/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "BFS and DFS"
        }
       ]
      },
      {
       "t": "Strongly Connected Components",
       "k": "problem",
       "items": [
        {
         "id": "3a4cff201c",
         "t": "The Bottom of a Graph",
         "u": "https://www.spoj.com/problems/BOTTOM/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Strongly Connected Components"
        },
        {
         "id": "4ee6f323c1",
         "t": "Fake Tournament",
         "u": "https://www.spoj.com/problems/TOUR/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Strongly Connected Components"
        }
       ]
      },
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "23004ee89a",
         "t": "Finding Bridges in Graphs",
         "u": "https://cp-algorithms.com/graph/bridge-searching.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=aZXi1unBdJA",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "86342a06b5",
         "t": "Articulation Points",
         "u": "https://github.com/williamfiset/Algorithms/blob/master/slides/graphtheory/bridges_and_articulation_points.pdf",
         "k": "read",
         "d": 0,
         "p": "github.com",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=aZXi1unBdJA",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "1acaa5d456",
         "t": "Dijkstra's Shortest path",
         "u": "https://cp-algorithms.com/graph/dijkstra_sparse.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=pSqmAO-m7Lk",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "725e078a18",
         "t": "Bellman Ford algorithm",
         "u": "https://cp-algorithms.com/graph/bellman_ford.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "832a4c8340",
         "t": "Floyd Warshall's algorithm",
         "u": "https://cp-algorithms.com/graph/all-pair-shortest-path-floyd-warshall.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=4NQ3HnhyNfQ",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "f41fd77b3e",
         "t": "Kruska's Minimum Spanning Tree",
         "u": "https://cp-algorithms.com/graph/mst_kruskal.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=JZBQLXgSGfs",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        },
        {
         "id": "ffae67fb9c",
         "t": "Prim's MST Algorithm",
         "u": "https://cp-algorithms.com/graph/mst_prim.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=jsmMtJpPnhU",
         "m": 1,
         "w": 2,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Problems: Biconnected Components",
       "k": "problem",
       "items": [
        {
         "id": "d58e0b13c5",
         "t": "UVa 00315: Network",
         "u": "https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=670&page=show_problem&problem=251",
         "k": "problem",
         "d": 0,
         "p": "UVa",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Biconnected Components"
        },
        {
         "id": "510cb8f97a",
         "t": "UVa 00796: Critical Links",
         "u": "https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=670&page=show_problem&problem=737",
         "k": "problem",
         "d": 0,
         "p": "UVa",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Biconnected Components"
        },
        {
         "id": "0049417378",
         "t": "CF 193A: Cutting Figure",
         "u": "http://codeforces.com/problemset/problem/193/A",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Biconnected Components"
        }
       ]
      },
      {
       "t": "Problems: Shortest Path",
       "k": "problem",
       "items": [
        {
         "id": "b8a61ec4a2",
         "t": "HE: Minimum Valid Path",
         "u": "https://www.hackerearth.com/practice/algorithms/graphs/graph-representation/practice-problems/algorithm/minimum-valid-path-3dc5bd03/",
         "k": "problem",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Shortest Path"
        },
        {
         "id": "9f2df894cf",
         "t": "CC: DIGJUMP",
         "u": "https://www.codechef.com/problems/DIGJUMP",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Shortest Path"
        },
        {
         "id": "18e5efe15c",
         "t": "CC: AMR14B",
         "u": "https://www.codechef.com/AMR14ROS/problems/AMR14B",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Shortest Path"
        },
        {
         "id": "c33a230903",
         "t": "SPOJ: Mice and Maze",
         "u": "https://www.spoj.com/problems/MICEMAZE/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Shortest Path"
        }
       ]
      },
      {
       "t": "Problems: Minimum Spanning Tree",
       "k": "problem",
       "items": [
        {
         "id": "4d988da0d0",
         "t": "SPOJ: BLINNET",
         "u": "https://www.spoj.com/problems/BLINNET/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Minimum Spanning Tree"
        },
        {
         "id": "b3a878cde2",
         "t": "HR: Roads in HackerLand",
         "u": "https://www.hackerrank.com/contests/june-world-codesprint/challenges/johnland/problem",
         "k": "problem",
         "d": 0,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Minimum Spanning Tree"
        },
        {
         "id": "e14c087942",
         "t": "CC: MST Queries",
         "u": "https://www.codechef.com/problems/MSTQS",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Minimum Spanning Tree"
        },
        {
         "id": "c66365ce59",
         "t": "SPOJ: KOICOST",
         "u": "https://www.spoj.com/problems/KOICOST/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Problems: Minimum Spanning Tree"
        }
       ]
      },
      {
       "t": "Contests",
       "k": "contest",
       "items": [
        {
         "id": "67fd2c5c39",
         "t": "DSA Learning Series: Week 8 - Graphs By CodeChef",
         "u": "https://www.codechef.com/LRNDSA08",
         "k": "contest",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 2,
         "s": "Contests"
        }
       ]
      }
     ]
    },
    {
     "n": 3,
     "title": "String Algorithms",
     "sections": [
      {
       "t": "Reading material",
       "k": "read",
       "items": [
        {
         "id": "54633fc8f5",
         "t": "Basics of String manipulation",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/basics-of-string-manipulation/tutorial/",
         "k": "read",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "de24d856d2",
         "t": "KMP algorithm",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/string-searching/tutorial/",
         "k": "read",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "a54a323b3e",
         "t": "Z algorithm",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/z-algorithm/tutorial/",
         "k": "read",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "03c1606ba7",
         "t": "Z algorithm II",
         "u": "https://cp-algorithms.com/string/z-function.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "ce1902f892",
         "t": "Manachar's algorithm",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/manachars-algorithm/tutorial/",
         "k": "read",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "b739374740",
         "t": "Manacher's algorithm II",
         "u": "https://cp-algorithms.com/string/manacher.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        },
        {
         "id": "4587b45023",
         "t": "Rabin-Karp and KMP TopCoder",
         "u": "https://www.topcoder.com/community/competitive-programming/tutorials/introduction-to-string-searching-algorithms/",
         "k": "read",
         "d": 0,
         "p": "TopCoder",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Reading material"
        }
       ]
      },
      {
       "t": "Problems on HackerEarth",
       "k": "problem",
       "items": [
        {
         "id": "4b4818d28f",
         "t": "Find the substrings",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/basics-of-string-manipulation/practice-problems/algorithm/find-the-substrings/",
         "k": "problem",
         "d": 2,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        },
        {
         "id": "33794940aa",
         "t": "The Cheapest Palindrome",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/basics-of-string-manipulation/practice-problems/algorithm/make-the-cheapest-palindrome-1/",
         "k": "problem",
         "d": 2,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        },
        {
         "id": "e3c414ee63",
         "t": "Largest Lexicographical Rotation II",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/string-searching/practice-problems/algorithm/largest-lexicographical-rotation-ii/",
         "k": "problem",
         "d": 2,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        },
        {
         "id": "861ca0eaf7",
         "t": "Monk and Monster",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/string-searching/practice-problems/algorithm/monk-and-monster-1acbb78c/",
         "k": "problem",
         "d": 2,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        },
        {
         "id": "db42cd307e",
         "t": "Prefix Number",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/z-algorithm/practice-problems/algorithm/prefix-number-f5c76976/",
         "k": "problem",
         "d": 3,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        },
        {
         "id": "331e37b911",
         "t": "Last Forever",
         "u": "https://www.hackerearth.com/practice/algorithms/string-algorithm/manachars-algorithm/practice-problems/algorithm/last-forever/",
         "k": "problem",
         "d": 3,
         "p": "HackerEarth",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerEarth"
        }
       ]
      },
      {
       "t": "Problems on HackerRank",
       "k": "problem",
       "items": [
        {
         "id": "085e895dcf",
         "t": "Sherlock and the Valid String",
         "u": "https://www.hackerrank.com/challenges/sherlock-and-valid-string/problem",
         "k": "problem",
         "d": 1,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerRank"
        },
        {
         "id": "d025a9294b",
         "t": "Highest Value Palindrome",
         "u": "https://www.hackerrank.com/challenges/richie-rich/problem",
         "k": "problem",
         "d": 1,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerRank"
        },
        {
         "id": "db6137ede4",
         "t": "Sherlock and Anagrams",
         "u": "https://www.hackerrank.com/challenges/sherlock-and-anagrams/problem",
         "k": "problem",
         "d": 2,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerRank"
        },
        {
         "id": "103631b9e8",
         "t": "Common Child",
         "u": "https://www.hackerrank.com/challenges/common-child/problem",
         "k": "problem",
         "d": 2,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerRank"
        },
        {
         "id": "b015fc1626",
         "t": "Build a Palindrome",
         "u": "https://www.hackerrank.com/challenges/challenging-palindromes/problem",
         "k": "problem",
         "d": 3,
         "p": "HackerRank",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on HackerRank"
        }
       ]
      },
      {
       "t": "Problems on Codeforces",
       "k": "problem",
       "items": [
        {
         "id": "6131f1dc5a",
         "t": "Petya and Exam",
         "u": "https://codeforces.com/problemset/problem/832/B",
         "k": "problem",
         "d": 1,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on Codeforces"
        },
        {
         "id": "6329ac4aba",
         "t": "Password",
         "u": "https://codeforces.com/problemset/problem/126/B",
         "k": "problem",
         "d": 2,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on Codeforces"
        },
        {
         "id": "5c8403900d",
         "t": "Prefixes and Suffixes",
         "u": "https://codeforces.com/problemset/problem/432/D",
         "k": "problem",
         "d": 3,
         "p": "Codeforces",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on Codeforces"
        }
       ]
      },
      {
       "t": "Problems on Codechef",
       "k": "problem",
       "items": [
        {
         "id": "42756e1294",
         "t": "Kira Loves Palindromes",
         "u": "https://www.codechef.com/APRIL19A/problems/KLPM/",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on Codechef"
        }
       ]
      },
      {
       "t": "Problems on SPOJ",
       "k": "problem",
       "items": [
        {
         "id": "9dca2bd30d",
         "t": "Word Puzzles",
         "u": "https://www.spoj.com/problems/WPUZZLES/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 1,
         "w": 3,
         "s": "Problems on SPOJ"
        }
       ]
      }
     ]
    },
    {
     "n": 4,
     "title": "Practice Contest",
     "sections": [
      {
       "t": "Practice Contest",
       "k": "contest",
       "items": [
        {
         "id": "7c01cc1e9f",
         "t": "ZCO Practice Contest",
         "u": "https://www.codechef.com/ZCOPRAC",
         "k": "contest",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 4,
         "s": "Week 4: Practice Contest"
        },
        {
         "id": "d03fc31c5d",
         "t": "INOI Problems",
         "u": "https://www.codechef.com/INOIPRAC",
         "k": "contest",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 4,
         "s": "Week 4: Practice Contest"
        },
        {
         "id": "635a3340ea",
         "t": "IARCS OPC Judge Problems",
         "u": "https://www.codechef.com/IARCSJUD",
         "k": "contest",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 1,
         "w": 4,
         "s": "Week 4: Practice Contest"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "n": 2,
   "weeks": [
    {
     "n": 5,
     "title": "Data Structures",
     "sections": [
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "1415a50a32",
         "t": "Tutorial",
         "u": "https://cp-algorithms.com/data_structures/sparse-table.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=uUatD9AudXo",
         "m": 2,
         "w": 5,
         "s": "Reading Material"
        },
        {
         "id": "e90d97b509",
         "t": "Blog post",
         "u": "http://adilet.org/blog/sparse-table/",
         "k": "read",
         "d": 0,
         "p": "Blog",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Problems",
       "k": "problem",
       "items": [
        {
         "id": "32f85c5871",
         "t": "B. Maximum of Maximums of Minimums",
         "u": "https://codeforces.com/problemset/problem/872/B",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Problems"
        },
        {
         "id": "1c6c26e156",
         "t": "CGCDSSQ",
         "u": "https://codeforces.com/contest/475/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Problems"
        },
        {
         "id": "eb31df0eb7",
         "t": "D. R2D2 and Droid Army",
         "u": "https://codeforces.com/problemset/problem/514/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Problems"
        }
       ]
      },
      {
       "t": "Disjoint Set Union · Reading Material",
       "k": "read",
       "items": [
        {
         "id": "13a75a00c6",
         "t": "Tutorial",
         "u": "https://cp-algorithms.com/data_structures/disjoint_set_union.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": true,
         "vu": "https://www.youtube.com/watch?v=0jNmHPfA_yE",
         "m": 2,
         "w": 5,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Disjoint Set Union · Problems",
       "k": "problem",
       "items": [
        {
         "id": "7ee040f0d2",
         "t": "D. Roads not only in Berland",
         "u": "https://codeforces.com/contest/25/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Problems"
        },
        {
         "id": "1c1788319d",
         "t": "HackerEarth CodeMonk: DSU",
         "u": "https://www.hackerearth.com/challenges/competitive/code-monk-disjoint-set-union-union-find/",
         "k": "problem",
         "d": 0,
         "p": "HackerEarth",
         "v": false,
         "m": 2,
         "w": 5,
         "s": "Problems"
        }
       ]
      }
     ]
    },
    {
     "n": 6,
     "title": "Square Root Decomposition",
     "sections": [
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "afa0eb91f4",
         "t": "Tutorial 1: Base Concept + Mo's algorithm",
         "u": "https://cp-algorithms.com/data_structures/sqrt_decomposition.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        },
        {
         "id": "cce117f281",
         "t": "Tutorial 2",
         "u": "https://codeforces.com/blog/entry/20489",
         "k": "read",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        },
        {
         "id": "c8eb108ece",
         "t": "Tutorial 3 : Read the comments",
         "u": "https://codeforces.com/blog/entry/16883",
         "k": "read",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        },
        {
         "id": "ec508dae78",
         "t": "Tutorial 4 : Video Lecture, find slides in video description",
         "u": "https://www.youtube.com/watch?v=VGq6w9TlJBY",
         "k": "read",
         "d": 0,
         "p": "YouTube",
         "v": true,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        },
        {
         "id": "fa422d3611",
         "t": "Tutorial 5 : Exhaustive PDF",
         "u": "http://acm.math.spbu.ru/~sk1/mm/lections/mipt2016-sqrt/mipt-2016-burunduk1-sqrt.en.pdf",
         "k": "read",
         "d": 0,
         "p": "PDF",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        },
        {
         "id": "6bdc1ef9ce",
         "t": "Tutorial 6 : Mo's Algorithm",
         "u": "https://blog.anudeep2011.com/mos-algorithm/",
         "k": "read",
         "d": 0,
         "p": "Blog",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Problems",
       "k": "problem",
       "items": [
        {
         "id": "786e254118",
         "t": "CHEFXQ",
         "u": "https://www.codechef.com/problems/CHEFEXQ",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "0d20d6d589",
         "t": "RACETIME",
         "u": "https://www.spoj.com/problems/RACETIME",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "6bf04b1f69",
         "t": "GIVEAWAY",
         "u": "http://www.spoj.com/problems/GIVEAWAY/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "76385c2df1",
         "t": "13E",
         "u": "http://codeforces.com/contest/13/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "14d7a41d97",
         "t": "342E",
         "u": "https://codeforces.com/contest/342/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "601d5b3062",
         "t": "DQUERY",
         "u": "http://www.spoj.com/problems/DQUERY/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "619efa4285",
         "t": "375D",
         "u": "http://codeforces.com/problemset/problem/375/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "f2352e285a",
         "t": "840D",
         "u": "http://codeforces.com/contest/840/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "17dd3804d4",
         "t": "86D",
         "u": "https://codeforces.com/contest/86/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "1234da4fa9",
         "t": "398D",
         "u": "https://codeforces.com/contest/398/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "9e6da5b6cc",
         "t": "GERALD07",
         "u": "https://www.codechef.com/problems/GERALD07",
         "k": "problem",
         "d": 0,
         "p": "CodeChef",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        },
        {
         "id": "b5f39b5d8b",
         "t": "MKTHNUM",
         "u": "https://www.spoj.com/problems/MKTHNUM/",
         "k": "problem",
         "d": 0,
         "p": "SPOJ",
         "v": false,
         "m": 2,
         "w": 6,
         "s": "Problems"
        }
       ]
      }
     ]
    },
    {
     "n": 7,
     "title": "Segment Tree",
     "sections": [
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "e144b8963a",
         "t": "Tutorial",
         "u": "https://cp-algorithms.com/data_structures/segment_tree.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Problems",
       "k": "problem",
       "items": [
        {
         "id": "704c757092",
         "t": "D. Distinct Characters Queries",
         "u": "https://codeforces.com/problemset/problem/1234/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Problems"
        },
        {
         "id": "19cef23e54",
         "t": "A. Knight Tournament",
         "u": "https://codeforces.com/contest/356/problem/A",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Problems"
        },
        {
         "id": "6c04c42fe4",
         "t": "F. Ant colony",
         "u": "https://codeforces.com/contest/474/problem/F",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Problems"
        },
        {
         "id": "dd5e2ea4b9",
         "t": "E. Drazil and Park",
         "u": "https://codeforces.com/contest/515/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Problems"
        },
        {
         "id": "351255cc2e",
         "t": "C. DZY Loves Fibonacci Numbers",
         "u": "https://codeforces.com/contest/446/problem/C",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 7,
         "s": "Problems"
        }
       ]
      }
     ]
    },
    {
     "n": 8,
     "title": "Fenwick Tree",
     "sections": [
      {
       "t": "Reading Material",
       "k": "read",
       "items": [
        {
         "id": "60f060c340",
         "t": "Tutorial",
         "u": "https://cp-algorithms.com/data_structures/fenwick.html",
         "k": "read",
         "d": 0,
         "p": "cp-algorithms",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Reading Material"
        }
       ]
      },
      {
       "t": "Problems",
       "k": "problem",
       "items": [
        {
         "id": "c9401b8e8b",
         "t": "E. Little Artem and Time Machine",
         "u": "https://codeforces.com/contest/669/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Problems"
        },
        {
         "id": "6f5e61185c",
         "t": "E. Hanoi Factory",
         "u": "https://codeforces.com/contest/777/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Problems"
        },
        {
         "id": "6f0a43c5dc",
         "t": "C. Subsequences",
         "u": "https://codeforces.com/contest/597/problem/C",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Problems"
        },
        {
         "id": "026215cd5d",
         "t": "D. Ball",
         "u": "https://codeforces.com/contest/12/problem/D",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Problems"
        },
        {
         "id": "be6e01c9f8",
         "t": "E. Garlands",
         "u": "https://codeforces.com/contest/707/problem/E",
         "k": "problem",
         "d": 0,
         "p": "Codeforces",
         "v": false,
         "m": 2,
         "w": 8,
         "s": "Problems"
        }
       ]
      }
     ]
    }
   ]
  }
 ],
 "stats": {
  "problems": 78,
  "reading": 27,
  "contests": 10,
  "total": 115,
  "platforms": 15
 }
};
